# fly.toml app configuration file generated for awezmirza on 2024-12-18T05:54:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'awezmirza'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
